# Default values for castai-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Azure K8s App marketplace variables:
global:
  azure:
    images:
      agent:
        digest: <imageDigest>
        image: <imageName>
        registry: <imageRegistry>
      cpva:
        digest: sha256:f6c85b45bb5e8ce6077855425bdd03e93d41926dbf6b751af64ab1ea41e1755b
        image: cpvpa
        registry: registry.k8s.io/cpa

image:
  pullPolicy: IfNotPresent

replicaCount: 1
namespace: "castai-agent"

# labels to add to all resources
commonLabels: {}

# annotations to add to all resources
commonAnnotations: {}

nameOverride: ""
fullnameOverride: castai-agent

# Specifies whether a namespace should be created
createNamespace: false
# Specifies whether RBAC Clusterrole should be created
rbac:
  enabled: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

# Labels to be added to agent pods
podLabels: {}

# Cluster proportional vertical autoscaler for the agent deployment
# https://github.com/kubernetes-sigs/cluster-proportional-vertical-autoscaler
clusterVPA:
  enabled: true
  pollPeriodSeconds: 300

resources: {}

additionalEnv:
  PPROF_PORT: "6060"

additionalSecretEnv: {}

# URL to the API server
apiURL: "https://api.cast.ai"

# Token to be used for authorizing agent access to the API
apiKey: "PLACEHOLDER"

# Name of secret with Token to be used for authorizing agent access to the API
# apiKey and apiKeySecretRef are mutually exclusive
# The referenced secret must provide the token in .data["API_KEY"]
apiKeySecretRef: ""

# Name of the Kubernetes service provider
# one of: "eks", "gks", "aks", "kops"
provider: ""

priorityClass:
  enabled: true
  name: system-cluster-critical

# Pod toleration rules.
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: {}

# Pod node selector rules.
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
nodeSelector: {}

# Pod affinity rules.
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: NotIn
              values:
                - windows
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: provisioner.cast.ai/managed-by
              operator: In
              values:
                - cast.ai
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - castai-agent
          topologyKey: kubernetes.io/hostname

# Pod security context.
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
securityContext:
  runAsNonRoot: true
  fsGroup: 1002
  runAsGroup: 1002
  runAsUser: 1002
  seccompProfile:
    type: RuntimeDefault


# Container security context.
# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
