apiVersion: v2
name: castai-agent
description: CAST AI agent deployment chart.
type: application
version: 0.52.0
appVersion: "v0.42.2"
kubeversion: '>= 1.19'
annotations:
  charts.openshift.io/name: castai-agent