name: Release CNAB package

#on:
#  push:
#    branches:
#      - main
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  release-cnab-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Release CNAB package
        run: scripts/handle-cnab-package.sh
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          CNAB_ACTION: "RELEASE"
          AZURE_K8S_APP_MARKETPLACE_SP_ID: ${{ secrets.AZURE_K8S_APP_MARKETPLACE_SP_ID }}
          AZURE_K8S_APP_MARKETPLACE_SP_SECRET: ${{ secrets.AZURE_K8S_APP_MARKETPLACE_SP_SECRET }}
          AZURE_K8S_APP_MARKETPLACE_TENANT_ID: ${{ secrets.AZURE_K8S_APP_MARKETPLACE_TENANT_ID }}
          AZURE_K8S_APP_MARKETPLACE_REGISTRY_NAME: ${{ secrets.AZURE_K8S_APP_MARKETPLACE_REGISTRY_NAME }}